name: sanic-openapi3e

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.6.0,<3.7
  - aiohttp
  - black
  - isort
  - loguru
  - mypy
  - pip
  - pytest
  - pytest-cov
  - requests-async >=0.5.0
  - pip:
      - sanic >=19.6.0

