name: sanic-openapi3e

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.6.0,<3.7
  - aiohttp  # testing only
  - black  # build only
  - isort  # build only
  - mypy  # testing only
  - pip
  - pylint  # build only
  - pytest  # testing only
  - pytest-cov  # testing only
  - pyyaml >= 5.3.1
  # - requests-async >=0.5.0
  - pip:
      - sanic >= 20.12.0

